apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: test-hookrole
  namespace: default
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-delete-policy": before-hook-creation
rules:
- apiGroups: ["rbac.authorization.k8s.io"]
  resources: ["rolebindings", "roles"]
  verbs: ["get", "list"]
- apiGroups: [""]
  resources: ["secrets", "namespaces", "pods", "nodes", "services", "endpoints", "configmaps"]
  verbs: ["get", "list"]
- apiGroups: ["networking.k8s.io"]
  resources: ["ingresses"]
  verbs: ["get", "list"]
- apiGroups: ["networking.istio.io"]
  resources: ["virtualservices", "destinationrules", "gateways", "serviceentries"]
  verbs: ["get", "list"]
---
# Source: helm-crane/templates/tests/testrbac.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name:  test-hookrole-binding-default
  namespace: default
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-delete-policy": before-hook-creation
subjects:
- kind: ServiceAccount
  name: default
  namespace: default
roleRef:
  kind: Role
  name:  test-hookrole
  apiGroup: rbac.authorization.k8s.io
---
# Source: helm-crane/templates/tests/testhook.yaml
apiVersion: v1
kind: Pod
metadata:
  name: cranetesthook
  namespace: default
  annotations:
    "helm.sh/hook": test
    "helm.sh/hook-delete-policy": before-hook-creation
    "helm.sh/hook-container-name": cranetest-ctr
    "sidecar.istio.io/inject": "false"
spec:
  serviceAccountName: default
  automountServiceAccountToken: true
  #ttlSecondsAfterFinished: 90
  containers:
  - name: cranetest-ctr
    securityContext:
      runAsUser: 1337
      runAsGroup: 1337
      allowPrivilegeEscalation: false
      runAsNonRoot: true
    env:
    - name: WORKING_NAMESPACE
      value: "default"
    - name: ROLE_NAME
      value: crane-role
    - name: ROLE_BINDING_NAME
      value: crane-role-binding-default
    - name: SERVICE_ACCOUNT_NAME
      value: default
    - name: KUBERNETES_WEB_EXPOSE_TYPE
      value: "INGRESS"
    - name: KUBERNETES_WEB_EXPOSE_TLS_SECRET_NAME
      value: "wildcard-credential1"
    - name: DOCKER_REGISTRY
      value: "gcr.io/verdant-bulwark-278"
    image: gcr.io/verdant-bulwark-278/cranehook:latest
    imagePullPolicy: "Always"
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: 200m
        memory: 512Mi
    volumeMounts:
      - name: testhook-tmp
        mountPath: /tmp/testhook
  volumes:
    - name: testhook-tmp
      emptyDir: {}
  restartPolicy: "Never"