apiVersion: v1
kind: Pod
metadata:
  name: cranetestpod
  namespace: default
spec:
  serviceAccountName: default
  containers:
  - name: cranetestctr
    securityContext:
      runAsUser: 1337
      runAsGroup: 1337
      allowPrivilegeEscalation: false
      runAsNonRoot: true  
    env: 
    - name: WORKING_NAMESPACE
      value: "default"
    - name: ROLE_NAME
      value: "crane-s-role"
    - name: ROLE_BINDING_NAME
      value: "crane-s-role-binding-default"
    - name: SERVICE_ACCOUNT_NAME
      value: "default"
    - name: SV_ENABLE
      value: "true"
    - name: KUBERNETES_WEB_EXPOSE_TYPE
      value: "NGINX"
    image: "immnan/godebug:0.1.0"
    imagePullPolicy: "Always"
    resources:
      requests:
        memory: "256Mi"
        cpu: "100m"
      limits:
        memory: "512Mi"
        cpu: "250m"
  restartPolicy: "Always"
